### ISSUE TITLE
Other languages compatibility

### ISSUE THREAD

**Issue by yipfram** [LetsUpdate/CSN#2]
Hey,
I love what you did. I tried to include your code in a new chrome extension to make neptun more usable (new UI, and captcha resolver). I worked ;)

The only thing is that Captcha resolving only works for hungarian audio version. I would like to make it for the other languages. 
I guess that we only need to find the corresponding BASE_NUMBERPRINTS values. (tell me if i'm wrong haha)
Could you please explain to me how you found these numbers so i can make a new version with other languages support.
Thank you in advance ;)
Yipfram

**Comment by LetsUpdate** [comment]
Just manually find it,
Run the algorithm and than see what numbers does it return
Than match with the picture
