### ISSUE TITLE
Captcha külön ablakban

### ISSUE THREAD

**Issue by DMarci01** [LetsUpdate/CSN#3]
Óbudai Egyetem Neptun már külön ablakban kéri a Captcha-t, esetleg meg lehet oldani, hogy itt is be tudja írni?

![image](https://github.com/user-attachments/assets/7a1af48d-0e30-46f8-864d-d22a68643034)

**Comment by LetsUpdate** [comment]
Hát, en is ma láttam meg... Elv simán megoldható. Majd valamikor ránézek, de akár valamj contributor is megoldhatná🪓

**Comment by LetsUpdate** [comment]
De hogy erre mégis mi szükség volt?? Jó kérdés...

**Comment by boglarkla** [comment]
@LetsUpdate Az a baj hogy a CaptchaAudio link 404-et dob lmao jelenleg, szóval nem tudom hogy lehetne működésre bírni most a dolgokat :d

**Comment by LetsUpdate** [comment]
Igen, sajnos ez nagy gond. @boglarkla 
Lehet direkt a script miatt csinálták XD

dee ha a kép felismeréséből indulunk ki, van még remény...

**Comment by boglarkla** [comment]
@LetsUpdate Már ki is szedték az audio linkjét :)

**Comment by LetsUpdate** [comment]
@boglarkla és mindenki más!

Már van egy működő prototípusunk, de ez még messze van attól, hogy production-ready legyen.

Kulcsszavak: Docker, TensorFlow, Gunicorn (Flask), TensorFlow Serving, Webpack, Userscript

Ha van kedvetek segíteni, és érdekel titeket valamelyik terület, kérlek írjatok Discordon! (RED#4602)

Jelenleg rendelkezésre áll egy userscript, a Flask devserver és egy betanított modell.

Amiben segítségre lenne szükség:
- ~~A TensorFlow Serving beállítása~~
- A userscript felhasználóbarátabbá tétele. kis UI, hogy mit is csinál a script
- ~~A script(python) javítása, amely a karaktereket kivágja a képből felismerés előtt~~
- Talán egy mini weboldal

**Comment by boapps** [comment]
Hali! Nekem most BME-s neptunon (verzió: `2024.2.12 (2024. 08. 13.)`) nem jön be captcha-s ablak, amikor NPU be van kapcsolva. Nem tudom, hogy máshol is hasonló-e a helyzet. De ez alapján én arra következtetek, hogy ez kliens oldalról is triviálisan kijátszható.
Ettől még a tensorflow-s megoldás is izginek hangzik, de talán picit overkill.

**Comment by boglarkla** [comment]
@boapps  szia, probald ezzel: https://github.com/boglarkla/npu/releases/download/v2.4.0-fixed/npufix.user.js

par hete fixaltam, és nalunk feljon igy az ablak, csak neked kell kitölteni sorry :D

**Comment by boapps** [comment]
Köszi! Én mondjuk a "nem jön be captcha-s ablak"-ot úgy értettem, hogy (mentett login esetén) azonnal (3 sec után) bejelentkeztet átugorva minden captcha-t.

De a fixelt verzióval valóban csak a captcha jön be. Az OE-s neptun-ból egyel régebbi verzió fut, lehetséges, hogy ezzel függ össze.

**Comment by boglarkla** [comment]
@boapps  ohh, köszi az infót!:)))

**Comment by LetsUpdate** [comment]
> Hali! Nekem most BME-s neptunon (verzió: `2024.2.12 (2024. 08. 13.)`) nem jön be captcha-s ablak, amikor NPU be van kapcsolva. Nem tudom, hogy máshol is hasonló-e a helyzet. De ez alapján én arra következtetek, hogy ez kliens oldalról is triviálisan kijátszható.
> 
> Ettől még a tensorflow-s megoldás is izginek hangzik, de talán picit overkill.

Ha jól értem...
Akkor a szerver leszrja hogy jo-e a captcha vagy nem 😂

Ha ezzel van valami updatetek nyugodtan szoljatok amúgy!

**Comment by boapps** [comment]
Na nézegettem még egy kicsit a dolgot.

A BME-s neptun üres captchával is engedte a logint, ott nem volt check a backenden. (azért múltidő, mert sajna közben nálunk teljesen leszedték a captchát, csak a tárgyfelvétel idejére tiszteltek meg vele)

Viszont most megnéztem az OE neptunban van check a backenden, a request `captchaerror` errorcode-dal tér vissza. :(

**Comment by LetsUpdate** [comment]
Kint a [release](https://github.com/LetsUpdate/CSN/releases/tag/release_v1.0.2)!
Az esetek többségében működik, ha valami gond van szóljatok!
